Day_02/app/app.py
from flask import Flask
from .routes.usuario import usuario
from .routes.produto import produto
from .commands.userCommands import userCommands
from .extentions import database


def create_app(config_object="app.settings"):
    app = Flask(__name__)
    app.config.from_object(config_object)
    database.init_app(app)
    
    app.register_blueprint(usuario)
    app.register_blueprint(produto)
    app.register_blueprint(userCommands)
    
    return app

Day_02/app/routes/produto.py
from bson.objectid import ObjectId
from flask import Blueprint, render_template, request, session
from flask.helpers import flash, url_for
from werkzeug.utils import redirect
from ..extentions.database import mongo

produto = Blueprint("produto", __name__, url_prefix="/produtos")


@produto.route("/list")
def listProdutos():
    if "username" in session:
        produtos = mongo.db.produtos.find()
        return render_template("produtos/list.html", produtos=produtos)
    else:
        return redirect(url_for("usuario.index"))


@produto.route("/insert", methods=["GET", "POST"])
def inserirProduto():
    if request.method == "GET":
        return render_template("produtos/insert.html")
    else:
        nome = request.form.get("nome")
        quantidade = request.form.get("quantidade")
        preco = request.form.get("preco")
        categoria = request.form.get("categoria")
        estoque = request.form.get("estoque")

        if not nome or len(nome) > 50:
            flash("Campo 'nome' é obrigatório")
        elif not quantidade or not quantidade.isdigit() or int(quantidade) < 0:
            flash("Campo 'quantidade' é obrigatorio.")
        elif not categoria:
            flash("Campo 'categoria' é obrigatório.")
        elif not estoque:
            flash("Campo 'estoque' é obrigatório.")
        elif not preco:
            flash("Campo 'preco' é obrigatorio ")
        else:
            mongo.db.produtos.insert_one(
                {
                    "produto": nome,
                    "estoque": estoque,
                    "categoria": categoria,
                    "quantidade": quantidade,
                    "preco": preco,
                    "valor_total": (float(quantidade) * float(preco))     
                }
            )
            flash('Produto criado com sucesso')
        return redirect(url_for("produto.listProdutos"))


@produto.route("/edit", methods=["GET", "POST"])
def editarProduto():
    if request.method == "GET":
        idproduto = request.values.get("idproduto")

        if not idproduto:
            flash("Campo 'idproduto' é obrigatório.")
            return redirect(url_for("produto.listProdutos"))
        else:
            idp = mongo.db.produtos.find({"_id": ObjectId(idproduto)})
            produto = [i for i in idp]
            estoques = set()
            produtos = mongo.db.produtos.find()
            for pr in produtos:
                estoques.add(pr["estoque"])
            return render_template(
                "produtos/edit.html", produto=produto, estoques=estoques
            )
    else:
        idproduto = request.form.get("idproduto")
        nome = request.form.get("nome", "")
        categoria = request.form.get("categoria", "")
        estoque = request.form.get("estoque", "")
        preco = request.form.get("preco", "")
        quantidade = request.form.get("quantidade", "")

        categorias = ["Informática", "Papelaria"]

        if not idproduto:
            flash("Campo 'idproduto' é obrigatório e deve ser numérico.")

        elif not nome or len(nome) > 40:
            flash("Campo 'nome' é obrigatório e deve ter no máximo 40 caracteres.")

        elif not quantidade or not quantidade.isdigit() or int(quantidade) < 0:
            flash("Campo 'quantidade' é obrigatório e deve ser numérico.")

        elif not categoria or categoria not in categorias:
            flash("Campo 'categoria' é obrigatório ou é inválido.")
        elif not preco:
            flash("Campo 'preco' é obrigatorio ")
        else:
            total = float(preco) * float(quantidade)
            update = mongo.db.produtos.update(
                {"_id": ObjectId(idproduto)},
                {
                    "$set": {
                        "produto": nome,
                        "categoria": categoria,
                        "estoque": estoque,
                        "quantidade": quantidade,
                        "preco": preco,
                        "valor_total": total,
                    }
                },
            )
            flash("Produto alterado com sucesso!")
        return redirect(url_for("produto.listProdutos"))


@produto.route("/delete")
def deletarProduto():
    idproduto = request.values.get("idproduto", "")
    if not idproduto:
        flash("Campo 'idproduto' é obrigatório.")
    else:
        delete = mongo.db.produtos.delete_one({"_id": ObjectId(idproduto)})
    return redirect(url_for("produto.listProdutos"))

Day_02/app/routes/usuario.py
from flask import Blueprint, session, request, render_template, redirect, url_for, flash
from werkzeug.security import check_password_hash
from ..extentions.database import mongo


usuario = Blueprint("usuario", __name__)


@usuario.route("/")
def index():
    return redirect(url_for("usuario.login"))


@usuario.route("/main")
def main():
    if "username" in session:
        return render_template("usuarios/main.html")
    else:
        return redirect(url_for("usuario.index"))


@usuario.route("/login", methods=["GET", "POST"])
def login():
    if "username" in session:
        return redirect(url_for("usuario.main"))
    elif request.method == "POST":
        username = request.form.get("usuario")
        password = request.form.get("senha")

        user_found = mongo.db.users.find_one({"name": username})
        if user_found:
            user_val = user_found["name"]
            passwordcheck = user_found["password"]

            if check_password_hash(passwordcheck, password):
                session["username"] = user_val
                return redirect(url_for("usuario.main"))
            else:
                flash("Senha Incorreta", "error")
                return render_template("usuarios/login.html")
        else:
            flash("Usuário não encontrado")
            return render_template("usuarios/login.html")
    return render_template("usuarios/login.html")


@usuario.route("/logout", methods=["GET"])
def logout():
    session.pop("username", None)
    flash("Logout Efetuado!")
    return redirect(url_for("usuario.login"))

Day_02/app/templates/base.html
<!doctype html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Controle de Estoque</title>

        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet">    
    </head>
    <body>
        <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
            <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="{{ url_for('usuario.main') }}">Hands-On 4Linux</a>
            <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-nav px-3">
                <a class="nav-link" href="{{ url_for('usuario.logout') }}">Logout</a>
            </div>
        </header>
        <!-- navbar  -->
        <div class="container-fluid">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                    <div class="position-sticky pt-3">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link active" aria-current="page" href="{{ url_for('produto.listProdutos') }}">
                                    <span class="fa fa-shopping-cart"></span> Produtos 
                                </a>
                            </li>
                        </ul>
                    </div>
                </nav>
                <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                </main>
            </div>
        </div>>
        {% block content %}
        {% endblock %}

        <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/feather.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/Chart.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/dashboard.js') }}"></script>
    </body>

Day_02/app/templates/produtos/edit.html
{% extends "base.html" %}
{% block content %}
        <div class="container-fluid">
            <div class="row">

                <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                        <h1 class="h2">Alterar Produto</h1>
                    </div>

                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-success" role="alert">
                                  {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}

                    <form action="{{ url_for('produto.editarProduto') }}" method="post">
                        <input type="hidden" name="idproduto" value="{{ produto[0]['_id'] }}" id="idproduto" class="form-control" placeholder="Id do Produto" required>

                        <label for="nome" class="visually-hidden">Nome:</label>
                        <input type="text" name="nome" value="{{ produto[0]['produto'] }}" id="nome" class="form-control" placeholder="Nome do Produto" required autofocus>
                        
                        <label for="quantidade" class="visually-hidden">Quantidade:</label>
                        <input type="number" name="quantidade" value="{{ produto[0]['quantidade'] }}" id="quantidade" class="form-control" placeholder="Quantidade" required>

                        <label for="nome" class="visually-hidden">Preco:</label>
                        <input type="text" data-type="currency" name="preco" value="{{ produto[0]['preco'] }}" id="preco" class="form-control" placeholder="Nome do Produto" required autofocus>
                        
                        <label for="categoria" class="visually-hidden">Categoria</label>
                        <select class="form-select" name="categoria" id="categoria">
                            <option value="Placeholder" selected disabled>Selecione uma categoria</option>
                            <option value="Informática">Informática</option>
                            <option value="Papelaria">Papelaria</option>
                        </select>
                        <br>
                        <label for="estoque" class="visually-hidden">Estoque</label>
                        <select class="form-select" name="estoque" id="estoque">
                            <option value="Placeholder" selected disabled>Selecione uma Estoque</option>
                            {% for estoque in estoques %}
                            <option value="{{ estoque }}">{{ estoque }}</option>
                            {% endfor %}
                        </select>
                        <button class="w-100 btn btn-lg btn-primary" type="submit">Salvar</button>
                    </form>
                </main>
            </div>
        </div>
{% endblock %}

Day_02/app/templates/produtos/insert.html
{% extends "base.html" %}
{% block content %}
        <div class="container-fluid">
            <div class="row">


                <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                        <h1 class="h2">Adicionar Novo Produto</h1>
                    </div>

                    {% with messages = get_flashed_messages() %}
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-warning" role="alert">
                                  {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}

                    <form action="{{ url_for('produto.inserirProduto') }}" method="post">
                        <label for="nome" class="visually-hidden">Nome:</label>
                        <input type="text" name=nome id="nome" class="form-control" placeholder="Nome do Produto" required autofocus>

                        <label for="quantidade" class="visually-hidden">Quantidade:</label>
                        <input type="number" name=quantidade id="quantidade" class="form-control" placeholder="Quantidade" required>

                        <label for="preco" class="visually-hidden">preço:</label>
                        <input type="text" data-type="currency" name=preco id="preco" class="form-control" placeholder="Preço" required>

                        <label for="categoria" class="visually-hidden">Categoria</label>
                        <select class="form-select" name="categoria" id="categoria">
                            <option value="Placeholder" selected disabled>Selecione uma categoria</option>
                            <option value="Informática">Informática</option>
                            <option value="Papelaria">Papelaria</option>
                            <option value="Manutencao">Manutenção</option>
                        </select>
                        <br>
                        <label for="estoque" class="visually-hidden">Estoque</label>
                        <select class="form-select" name="estoque" id="estoque">
                            <option value="Placeholder" selected disabled>Selecione uma Estoque</option>
                            <option value="predio Ada Lovelace">Prédio Ada Lovelace</option>
                            <option value="predio Albert Einstein">Prédio Albert Einstein</option>
                            <option value="predio Iam Murdock">Prédio Iam Murdock</option>
                            <option value="predio Alan Turing">Prédio Alan Turing</option>
                        </select>

                        <button class="w-100 btn btn-lg btn-primary" type="submit">Adicionar</button>
                    </form>
                </main>
            </div>
        </div>
{% endblock %}

Day_02/app/templates/produtos/list.html
{% extends "base.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Produtos em Estoque</h1>
                </div>
                <div class="table-responsive">

                    {% with messages = get_flashed_messages() %} {% if messages %} {% for message in messages %}
                    <div class="alert alert-success" role="alert">
                        {{ message }}
                    </div>
                    {% endfor %} {% endif %} {% endwith %}

                    <a href="{{ url_for('produto.inserirProduto') }}" class="btn btn-dark">Adicionar Novo Produto</a>
                    <table class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th>Produto</th>
                                <th>Categoria</th>
                                <th>Estoque</th>
                                <th>Quantidade</th>
                                <th>Preço</th>
                                <th>Valor Total</th>
                                <th>Editar</th>
                                <th>Excluir</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for produto in produtos %}
                            <tr>
                                <td> {{ produto['produto'] }} </td>
                                <td> {{ produto['categoria'] }} </td>
                                <td> {{ produto['estoque'] }} </td>
                                <td> {{ produto['quantidade'] }} </td>
                                <td> {{ produto['preco'] }} </td>
                                <td> {{ produto['valor_total'] }} </td>
                                <td><a href="{{ url_for('produto.editarProduto', idproduto=produto['_id']) }}">Editar</a></td>
                                <td><a href="{{ url_for('produto.deletarProduto', idproduto=produto['_id']) }}">Excluir</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </main>
        </div>
    </div>
{% endblock %}

Day_02/app/templates/usuarios/login.html
<!doctype html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Controle de Estoque</title>

        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('static', filename='css/signin.css') }}" rel="stylesheet">
    </head>
    <body class="text-center">
        <main class="form-signin">
            <form action="/login" method="POST">
                <a><h1>Hands-on 4linux</h1></a>

                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-danger" role="alert">
                              {{ message }}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}

                <label for="login" class="visually-hidden">Login</label>
                <input type="text" name=usuario id="login" class="form-control" placeholder="Login" required autofocus>
                <label for="senha" class="visually-hidden">Senha</label>
                <input type="password" name=senha id="senha" class="form-control" placeholder="Senha" required>

                <button class="w-100 btn btn-lg btn-primary" type="submit">Login</button>
            </form>
        </main>
    </body>
</html>

Day_02/app/templates/usuarios/main.html
{% extends "base.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    <h1 class="h2">Sistema de Controle de estoque consolidado</h1>
                </div>
                <div>
                    <h2 class="h4">Funcionalidades de produtos:</h2>
                    <br>
                    <ul class="h5">
                        <li>Listar produtos dentro dos estoques.</li>
                        <br>
                        <li>Adicionar produtos dentro dos estoques.</li>
                        <br>
                        <li>Editar produtos dentro dos estoques.</li>
                        <br>
                        <li>Remover produtos dentro dos estoques.</li>
                    </ul>
                </div>
            </main>
        </div>
    </div>
{% endblock %}